const adjectives = [
  "Cursed",
  "Dangerous",
  "Lost",
  "Electric",
  "Invisible",
  "Forbidden",
  "Explosive",
  "Chaotic",
  "Fast",
  "Broken",
  "Ultimate",
  "Revenge",
  "Midnight",
  "Galactic",
  "Shattered",
  "Atomic",
  "Savage",
  "Velvet",
  "Crimson",
  "Golden",
  "Frozen",
  "Haunted",
  "Neon",
  "Secret",
  "Deadly",
  "Wild",
  "Toxic",
  "Phantom",
  "Infernal",
  "Solar",
  "Moonlit",
  "Digital",
  "Silent",
  "Raging",
  "Turbo",
  "Lethal",
  "Mutant",
  "Wicked",
  "Radiant",
  "Savory",
  "Monstrous",
  "Vengeful",
  "Cyber",
  "Ruthless",
  "Unholy",
  "Doomed",
  "Furious",
  "Ancient",
  "Royal",
  "Gritty",
  "Demonic",
  "Twisted",
  "Fearless",
  "Mechanical",
  "Venomous",
  "Brutal",
  "Dazzling",
  "Merciless",
  "Hollow",
  "Burning",
  "Viral",
  "Obsidian",
  "Radioactive",
  "Epic",
  "Sinister",
  "Glorious",
  "Savaged",
  "Fallen",
  "Chrome",
  "Shadow",
  "Bloody",
  "Iron",
  "Lucky",
  "Massive",
  "Rogue",
  "Ghostly",
  "Fatal",
  "Prime",
  "Dirty",
  "Mysterious",
  "Thunderous",
  "Hyper",
  "Shadowy",
  "Stormy",
  "Cosmic",
  "Mythic",
  "Distant",
  "Vicious",
  "Heroic",
  "Darkened",
  "Wandering",
  "Feral",
  "Quantum",
  "Dreadful",
  "Infinite",
  "Mad",
  "Retro",
  "Nuclear",
  "Bizarre",
  "Magnetic",
  "Electric",
  "Inferno",
  "Steel",
  "Chaotic",
  "Hilarious",
  "Unstable",
  "Cryptic",
  "Hunted",
  "Corrupted",
  "Supreme",
];

const movieWords = [
  "Goblin",
  "Popcorn",
  "Blockbuster",
  "Critic",
  "Sequel",
  "Spoiler",
  "Oscar",
  "Couch",
  "Director",
  "Franchise",
  "Tomato",
  "VHS",
  "Cinema",
  "Screenplay",
  "Rating",
  "Projector",
  "Premiere",
  "Ticket",
  "Reboot",
  "Zombie",
  "Alien",
  "Monster",
  "Ninja",
  "Samurai",
  "Detective",
  "Cowboy",
  "Pirate",
  "Robot",
  "Dragon",
  "Villain",
  "Hero",
  "Wizard",
  "Spy",
  "Mercenary",
  "Streamer",
  "Reviewer",
  "Actor",
  "Producer",
  "Studio",
  "Theater",
  "Script",
  "Camera",
  "Soundtrack",
  "Trailer",
  "Marathon",
  "Binge",
  "Saga",
  "Empire",
  "Legend",
  "Chronicle",
  "Apocalypse",
  "Carnival",
  "Dimension",
  "Portal",
  "Highway",
  "Kingdom",
  "Labyrinth",
  "Outlaw",
  "Mutant",
  "Creature",
  "Titan",
  "Warlord",
  "Phantom",
  "Gladiator",
  "Prophecy",
  "Galaxy",
  "Arena",
  "Machine",
  "Hunter",
  "Commander",
  "Assassin",
  "Champion",
  "Knight",
  "Specter",
  "Overlord",
  "Rebellion",
  "Voyager",
  "Beast",
  "Clown",
  "Puppet",
  "Ranger",
  "Nomad",
  "Predator",
  "Bandit",
  "Outcast",
  "Traveler",
  "Champion",
  "Tornado",
  "Dream",
  "Nightmare",
  "Experiment",
  "Survivor",
  "Judge",
  "Executioner",
  "Passenger",
  "Conspiracy",
  "Virus",
  "Clone",
  "Prisoner",
  "Mastermind",
  "Cult",
  "Agency",
  "Operation",
  "Mission",
  "Signal",
  "Frequency",
  "Broadcast",
  "Reality",
  "Universe",
  "Shadow",
  "Prophet",
  "Warrior",
  "Guardian",
  "Engineer",
  "Raider",
  "Bounty",
];

const endings = [
  "Returns",
  "Reloaded",
  "Strikes Back",
  "Forever",
  "Part II",
  "Origins",
  "vs The World",
  "in Space",
  "Unleashed",
  "of Doom",
  "Resurrection",
  "The Reckoning",
  "Awakens",
  "Rises",
  "Begins",
  "After Dark",
  "of Chaos",
  "Lives Again",
  "Eternal",
  "Beyond Time",
  "Reborn",
  "Ascension",
  "Endgame",
  "Under Siege",
  "The Final Cut",
  "No Mercy",
  "The Return",
  "The Last Stand",
  "Forevermore",
  "Underground",
  "At Midnight",
  "from Hell",
  "from Beyond",
  "Revenge Tour",
  "The Director's Cut",
  "Ultimate Edition",
  "and the Lost City",
  "and the Phantom Menace",
  "and the Broken Sword",
  "and the Cosmic Storm",
  "of the Future",
  "of the Ancients",
  "of Destiny",
  "The Movie",
  "vs Humanity",
  "vs Reality",
  "in 3D",
  "The Musical",
  "The Animated Series",
  "Part III",
  "Part IV",
  "The Prequel",
  "The Sequel",
  "The Crossover",
  "The Untold Story",
  "The Revenge",
  "The Return of Doom",
  "Maximum Velocity",
  "Turbo Edition",
  "Deluxe Edition",
  "The Beginning",
  "The Conclusion",
  "The Awakening",
  "The Experiment",
  "The Mutation",
  "The Collapse",
  "The Invasion",
  "The Infection",
  "World Tour",
  "Across the Universe",
  "Across Time",
  "from Another Planet",
  "of the Dead",
  "of the Living Dead",
  "vs Zombies",
  "vs Aliens",
  "vs Robots",
  "vs Vampires",
  "The Next Generation",
  "The Reckoning Continues",
  "The Final Chapter",
  "Zero Hour",
  "Code Red",
  "Protocol X",
  "Dark Horizons",
  "Into the Abyss",
  "Beyond Infinity",
  "Operation Chaos",
  "Escape Plan",
  "The Collapse of Reality",
  "The Multiverse",
  "in the Multiverse",
  "Beyond the Stars",
  "No Way Home",
  "Homecoming",
  "Far From Home",
  "The Secret Files",
  "The Forbidden Archive",
  "Blood Moon",
  "The Last Survivor",
  "Infinite Warfare",
  "Dawn of Chaos",
  "The Great Disaster",
  "The Reckoning Begins",
  "Rise of the Machines",
  "The Clone Wars",
  "The Hidden Truth",
  "The Blackout",
  "The Crimson Hour",
  "Maximum Carnage",
  "Night Shift",
  "Last Blood",
  "The Search Continues",
];

export function generateGameName() {
  const adjective =
    adjectives[Math.floor(Math.random() * adjectives.length)];

  const movieWord =
    movieWords[Math.floor(Math.random() * movieWords.length)];

  const ending =
    endings[Math.floor(Math.random() * endings.length)];

  return `${adjective} ${movieWord} ${ending}`;
}