  const winnerPhrases = [
    "Certified Rotten Genius",
    "The IMDb Oracle Has Spoken",
    "Critics Fear This Player",
    "Cinema Champion",
    "Box Office Beast",
    "Rotten Tomatoes Called. They're Nervous.",
    "The Sequel Nobody Could Beat",
    "Master of Movie Ratings",
    "This Player Deserves an Oscar",
    "Letterboxd Legend",
    "Critically Acclaimed",
    "The Franchise Continues",
    "Popcorn Prophet",
    "The Ratings Were Rigged (Maybe)",
    "Too Cinephile To Fail",
    "Straight To The Hall Of Fame",
    "The Final Cut Belongs To You",
    "Professional Couch Critic",
    "Viewer Discretion Advised",
    "Peak Cinema Achieved",
    "Now Showing: Absolute Dominance",
    "5 Stars. No Notes.",
    "The Audience Went Wild",
    "Academy Award For Best Guessing",
    "The Critics Stand Defeated",
    "This Win Was Directed By Christopher Nolan",
    "The Plot Twist Nobody Saw Coming",
    "The Chosen One",
    "Certified Fresh Victory",
    "A24 Wishes They Made This Ending",
    "The Multiverse's Greatest Guesser",
    "The Last Cinebender",
    "An Absolute Box Office Smash",
    "Built Different In IMAX",
    "The Ratings Assassin",
    "Streaming Worldwide Now",
    "The Hero Hollywood Needed",
    "Movie Night MVP",
    "One Guess To Rule Them All",
    "The Ratings Reaper",
    "Cinematic Royalty",
    "The Ultimate Director’s Cut",
    "Too Fast Too Accurate",
    "Viewer Rating: Legendary",
    "The Rotten Tomato Destroyer",
    "Lights. Camera. Victory.",
    "The Main Character Won Again",
    "Based On A True Skill Issue",
    "Cinema Has Peaked",
    "The End Credits Rolled For Everyone Else",
];

export function getWinnerPhrase() {
    return winnerPhrases[
        Math.floor(Math.random() * winnerPhrases.length)
    ];
}